"""Golden-fixture test for the BBOT adapter (ADR-0002 checklist).

`tests/fixtures/bbot-example.jsonl` was **generated by BBOT 3.0.1's own
serializer** (`Event.json()`), not hand-written, so the field shapes here
are the real ones rather than a plausible reconstruction. Two lines were
appended deliberately: a malformed one, and a `FINDING` event Glean has no
schema home for.
"""

from __future__ import annotations

import json
from pathlib import Path

from glean_osint.adapters.base import ScanContext
from glean_osint.adapters.bbot import BbotAdapter

FIXTURE = Path(__file__).parent.parent / "fixtures" / "bbot-example.jsonl"

CTX = ScanContext(target="tessno.com", collected_at="2026-08-18T00:00:00Z")


def _parse() -> object:
    return BbotAdapter().parse(FIXTURE.read_bytes(), CTX)


def test_the_apex_is_a_domain_and_the_rest_are_subdomains() -> None:
    result = _parse()

    by_type: dict[str, set[str]] = {}
    for entity in result.entities:
        by_type.setdefault(entity.type, set()).add(entity.value)

    assert by_type["domain"] == {"tessno.com"}
    assert by_type["subdomain"] == {"api.tessno.com", "beta.tessno.com"}


def test_every_mapped_event_type_produces_its_entity() -> None:
    """A firehose is only worth wiring if the types it adds actually land."""
    result = _parse()

    types = {e.type for e in result.entities}

    assert types == {"domain", "subdomain", "ip_address", "service", "email_address", "web_tech"}


def test_technology_is_read_from_data_json_not_data() -> None:
    """The detail that is not guessable: `Event.json()` branches on the
    Python type of the payload, so dict-valued events serialize under
    `data_json` and reading only `data` drops them silently."""
    result = _parse()

    tech = [e for e in result.entities if e.type == "web_tech"]

    assert [e.value for e in tech] == ["cloudflare"]
    assert any(
        edge.relation == "runs_tech" and edge.source_id == "subdomain:api.tessno.com"
        for edge in result.edges
    )


def test_an_open_port_becomes_a_service_keyed_like_httpx() -> None:
    """`service:<host>:<port>` has to match what HttpxAdapter emits, or
    dedup cannot join the two tools' views of one service (ADR-0003)."""
    result = _parse()

    service = next(e for e in result.entities if e.type == "service")

    assert service.id == "service:api.tessno.com:443"
    assert service.attributes["port"] == 443
    assert service.attributes["protocol"] == "tcp"
    assert any(
        edge.relation == "exposes_service" and edge.target_id == service.id for edge in result.edges
    )


def test_resolved_hosts_on_the_event_become_a_resolves_to_edge() -> None:
    """Positive DNS observation carried on the event itself — no second
    lookup, and no inference past what BBOT recorded."""
    result = _parse()

    assert any(
        edge.source_id == "subdomain:api.tessno.com"
        and edge.target_id == "ip_address:104.21.9.204"
        and edge.relation == "resolves_to"
        for edge in result.edges
    )


def test_the_finding_module_is_recorded_as_an_attribute_not_as_the_tool() -> None:
    """Same precedent as `subfinder_source`: the tool is the source, its
    own internal modules are traceability detail."""
    result = _parse()

    beta = next(e for e in result.entities if e.value == "beta.tessno.com")

    assert beta.attributes["bbot_module"] == "hackertarget"
    assert {p.source_tool for e in result.entities for p in e.provenance} == {"bbot"}


def test_an_unmapped_event_type_is_ignored_rather_than_counted_as_damage() -> None:
    """The fixture's `FINDING` line is well-formed and simply has no home
    in Glean's schema. Counting it as `skipped` would bury a real parse
    failure in noise — `skipped` means damaged, not uninteresting."""
    result = _parse()

    assert result.skipped == 1  # the malformed line only, not FINDING
    assert not any("interesting thing" in e.value for e in result.entities)


def test_one_malformed_line_costs_one_event_not_the_run() -> None:
    """With a firehose this is the difference between losing a record and
    losing a scan (ADR-0002 D5)."""
    raw = (
        b'{"type":"DNS_NAME","data":"a.tessno.com","tags":[]}\n'
        b"NOT JSON\n"
        b'{"type":"DNS_NAME","data":"b.tessno.com","tags":[]}\n'
    )

    result = BbotAdapter().parse(raw, CTX)

    assert result.skipped == 1
    assert {e.value for e in result.entities} == {"a.tessno.com", "b.tessno.com"}


def test_parsing_never_materialises_the_whole_stream(monkeypatch) -> None:  # type: ignore[no-untyped-def]
    """ADR-0002 Q3, resolved as line-by-line. Pinned by proving the adapter
    never hands the whole buffer to `json.loads` — a whole-file parse would
    show up here as a single call carrying every line."""
    seen: list[int] = []
    real_loads = json.loads

    def counting_loads(text: str, *args: object, **kwargs: object) -> object:
        seen.append(len(text))
        return real_loads(text, *args, **kwargs)

    monkeypatch.setattr(json, "loads", counting_loads)
    raw = FIXTURE.read_bytes()

    BbotAdapter().parse(raw, CTX)

    assert seen, "nothing was parsed at all"
    # Every decode saw one line, so the largest is far below the buffer.
    assert max(seen) < len(raw)


def test_an_empty_capture_is_not_an_error() -> None:
    result = BbotAdapter().parse(b"", CTX)

    assert result.entities == []
    assert result.skipped == 0


def test_the_command_restricts_bbot_to_passive_modules() -> None:
    """Without `-rf passive` BBOT will port-scan and brute-force. The
    charter requires that be a separate explicit opt-in, so it must not be
    reachable through this adapter's default invocation."""
    command = BbotAdapter().build_command("tessno.com")

    assert command is not None
    assert "-rf" in command and "passive" in command
    assert "-y" in command  # non-interactive; it otherwise waits on a prompt
